name: extract-tapermonkey-scripts-v2

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'input zip/tar file full path'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pwd
      - run: tree -a -I .git
      - run: echo "The input path is:[${{ inputs.path }}]"
      - run: pip install leveldb
      - run: python py-2.py "${{ inputs.path }}"
      - run: tree -a -I .git

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-tampermonkey-extract-output
          path: |
            extract_tampermonkey_script_output
            github-action-run.log

      - run: echo finished
